### ISSUE TITLE
Unit tests fail (Elixir 1.1.1)

### ISSUE THREAD

**Issue by chilicat** [zeromq/exzmq#15]
Just installed elixir the first time and wanted to get right into using it with exzmq. Noticed that the tests fail

    elixir -v
    Elixir 1.1.1

    mix test
    ......
    
      1) test open a rep socket and wait time out (ExzmqTest)
         test/exzmp_test.exs:117
             ** (MatchError) no match of right hand side value: {:error, {{:badmatch, {:error, :eaddrinuse}},     [{:gen_listener_tcp, :init, 1, [file: 'src/gen_listener_tcp.erl', line: 101]}, {:gen_server, :init_it, 6, [file:     'gen_server.erl', line: 328]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}
         stacktrace:
       test/exzmp_test.exs:119
    ...

**Comment by c-rack** [comment]
Welcome on board @chilicat!

Just freshly checked out and tried on my own; all tests are passing.

The error message `{:error, :eaddrinuse}` says that another process is listening on port 5555 on your system. If you are on Linux, try `netstat -tulpen` to see which process is using that port and try again after stopping that process.
