### ISSUE TITLE
Can you make it Elixir 0.15.1 compatible?

### ISSUE THREAD

**Issue by jamesaspinwall** [zeromq/exzmq#7]
I get the error message:

Erlang/OTP 17 [erts-6.1] [source-d2a4c20] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

==> gen_listener_tcp (compile)
Compiled src/gen_listener_tcp.erl

== Compilation error on file lib/exzmq/socket/dealer.ex ==
** (CompileError) lib/exzmq/socket/dealer.ex:6: undefined function defrecord/2
    (stdlib) lists.erl:1352: :lists.mapfoldl/3
    (elixir) src/elixir_exp.erl:49: :elixir_exp.expand/2
    (elixir) src/elixir.erl:206: :elixir.quoted_to_erl/3
    (stdlib) erl_eval.erl:657: :erl_eval.do_apply/6
    (elixir) src/elixir.erl:175: :elixir.erl_eval/3

**Comment by c-rack** [comment]
@jamesaspinwall can we close this issue? Elixir is now >= 1.1 and exzmq now supports that.

**Comment by c-rack** [comment]
Elixir 0.15 is outdated and Elixir 1.2 is supported
